export const CONSTRUCTOR_ARGUMENTS_SYMBOL_IDENTIFIER = `___CTOR_ARGS___`;
export const TYPE_NODE_CONSOLE_LOG_MARK = `___DI_COMPILER_TYPE_NODE_MARK___`;
export const DI_CONTAINER_NAME = "DIContainer";
