export const CONSTRUCTOR_ARGUMENTS_SYMBOL_IDENTIFIER: string = `___CTOR_ARGS___`;
export const CONSTRUCTOR_ARGUMENTS_SYMBOL: unique symbol = Symbol.for(
  CONSTRUCTOR_ARGUMENTS_SYMBOL_IDENTIFIER
);
export const DI_CONTAINER_NAME = "DIContainer";
